// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller/teacher-controller.proto

package controller

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
	types "types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestInput struct {
	Department           *types.Department `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RequestInput) Reset()         { *m = RequestInput{} }
func (m *RequestInput) String() string { return proto.CompactTextString(m) }
func (*RequestInput) ProtoMessage()    {}
func (*RequestInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0c6bf54b94e385, []int{0}
}

func (m *RequestInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInput.Unmarshal(m, b)
}
func (m *RequestInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInput.Marshal(b, m, deterministic)
}
func (m *RequestInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInput.Merge(m, src)
}
func (m *RequestInput) XXX_Size() int {
	return xxx_messageInfo_RequestInput.Size(m)
}
func (m *RequestInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInput.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInput proto.InternalMessageInfo

func (m *RequestInput) GetDepartment() *types.Department {
	if m != nil {
		return m.Department
	}
	return nil
}

type ResponseMessage struct {
	TeacherList          []*types.Teacher `protobuf:"bytes,1,rep,name=teacherList,proto3" json:"teacherList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResponseMessage) Reset()         { *m = ResponseMessage{} }
func (m *ResponseMessage) String() string { return proto.CompactTextString(m) }
func (*ResponseMessage) ProtoMessage()    {}
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_db0c6bf54b94e385, []int{1}
}

func (m *ResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMessage.Unmarshal(m, b)
}
func (m *ResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMessage.Marshal(b, m, deterministic)
}
func (m *ResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMessage.Merge(m, src)
}
func (m *ResponseMessage) XXX_Size() int {
	return xxx_messageInfo_ResponseMessage.Size(m)
}
func (m *ResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMessage proto.InternalMessageInfo

func (m *ResponseMessage) GetTeacherList() []*types.Teacher {
	if m != nil {
		return m.TeacherList
	}
	return nil
}

func init() {
	proto.RegisterType((*RequestInput)(nil), "controller.RequestInput")
	proto.RegisterType((*ResponseMessage)(nil), "controller.ResponseMessage")
}

func init() {
	proto.RegisterFile("controller/teacher-controller.proto", fileDescriptor_db0c6bf54b94e385)
}

var fileDescriptor_db0c6bf54b94e385 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4b, 0xc6, 0x30,
	0x10, 0x86, 0xfd, 0x10, 0x1c, 0x2e, 0x45, 0x69, 0x04, 0x29, 0x75, 0x91, 0xba, 0x74, 0x31, 0x6a,
	0xfd, 0x05, 0x5a, 0x51, 0x04, 0x5d, 0x82, 0x93, 0x4e, 0xb5, 0x1e, 0x2a, 0xd4, 0x24, 0xe6, 0xae,
	0x83, 0xff, 0x5e, 0x6c, 0xf2, 0xb5, 0xe9, 0xfa, 0xbc, 0x4f, 0x2e, 0xf7, 0x1e, 0x9c, 0xf6, 0xd6,
	0xb0, 0xb7, 0xc3, 0x80, 0xfe, 0x9c, 0xb1, 0xeb, 0x3f, 0xd1, 0x9f, 0x2d, 0x48, 0x39, 0x6f, 0xd9,
	0x4a, 0x58, 0x48, 0x79, 0xc8, 0xbf, 0x0e, 0x69, 0xeb, 0x06, 0xa1, 0x3c, 0x0a, 0xf0, 0x1d, 0x5d,
	0xe7, 0xf9, 0x1b, 0x0d, 0x07, 0x5e, 0x5d, 0x43, 0xa6, 0xf1, 0x67, 0x44, 0xe2, 0x07, 0xe3, 0x46,
	0x96, 0x97, 0x00, 0x8b, 0x53, 0x6c, 0x4e, 0x36, 0xb5, 0x68, 0x72, 0x35, 0x3d, 0x56, 0xb7, 0x73,
	0xa0, 0x13, 0xa9, 0x6a, 0xe1, 0x40, 0x23, 0x39, 0x6b, 0x08, 0x9f, 0x90, 0xa8, 0xfb, 0x40, 0x79,
	0x01, 0x22, 0x7e, 0xff, 0xf8, 0x45, 0xff, 0x63, 0x76, 0x6b, 0xd1, 0xec, 0xc7, 0x31, 0xcf, 0x21,
	0xd1, 0xa9, 0xd2, 0xbc, 0x42, 0x1e, 0x79, 0x3b, 0x37, 0x91, 0x77, 0x20, 0xee, 0x91, 0x23, 0x27,
	0x59, 0xa8, 0xa4, 0x77, 0xba, 0x75, 0x79, 0xbc, 0x4e, 0x56, 0xcb, 0x54, 0x3b, 0x37, 0xd9, 0x4b,
	0x72, 0x9f, 0xb7, 0xbd, 0xa9, 0xf9, 0xd5, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x7b, 0x37,
	0x54, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeacherControllerClient is the client API for TeacherController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeacherControllerClient interface {
	GetTeachers(ctx context.Context, in *RequestInput, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type teacherControllerClient struct {
	cc *grpc.ClientConn
}

func NewTeacherControllerClient(cc *grpc.ClientConn) TeacherControllerClient {
	return &teacherControllerClient{cc}
}

func (c *teacherControllerClient) GetTeachers(ctx context.Context, in *RequestInput, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/controller.TeacherController/GetTeachers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeacherControllerServer is the server API for TeacherController service.
type TeacherControllerServer interface {
	GetTeachers(context.Context, *RequestInput) (*ResponseMessage, error)
}

func RegisterTeacherControllerServer(s *grpc.Server, srv TeacherControllerServer) {
	s.RegisterService(&_TeacherController_serviceDesc, srv)
}

func _TeacherController_GetTeachers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeacherControllerServer).GetTeachers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.TeacherController/GetTeachers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeacherControllerServer).GetTeachers(ctx, req.(*RequestInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeacherController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.TeacherController",
	HandlerType: (*TeacherControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTeachers",
			Handler:    _TeacherController_GetTeachers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller/teacher-controller.proto",
}
