// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/department.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Department struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TeacherList          []*Teacher `protobuf:"bytes,3,rep,name=teacherList,proto3" json:"teacherList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_b33ce02b3a238829, []int{0}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetTeacherList() []*Teacher {
	if m != nil {
		return m.TeacherList
	}
	return nil
}

func init() {
	proto.RegisterType((*Department)(nil), "types.Department")
}

func init() { proto.RegisterFile("types/department.proto", fileDescriptor_b33ce02b3a238829) }

var fileDescriptor_b33ce02b3a238829 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x4f, 0x49, 0x2d, 0x48, 0x2c, 0x2a, 0xc9, 0x4d, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x62, 0x05, 0x8b, 0x4b, 0x09, 0x43, 0xa4, 0x4b, 0x52, 0x13, 0x93, 0x33, 0x52,
	0x8b, 0x20, 0x72, 0x4a, 0x49, 0x5c, 0x5c, 0x2e, 0x70, 0xf5, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89,
	0xb9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x01, 0x17, 0x37, 0xd4,
	0x08, 0x9f, 0xcc, 0xe2, 0x12, 0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x3e, 0x3d, 0xb0, 0xe1,
	0x7a, 0x21, 0x10, 0x99, 0x20, 0x64, 0x25, 0x4e, 0xec, 0x51, 0x10, 0x17, 0x24, 0xb1, 0x81, 0xed,
	0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x25, 0xe6, 0x39, 0xa9, 0x00, 0x00, 0x00,
}
