// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/teacher.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Teacher struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Teacher) Reset()         { *m = Teacher{} }
func (m *Teacher) String() string { return proto.CompactTextString(m) }
func (*Teacher) ProtoMessage()    {}
func (*Teacher) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ade93e9f120fc16, []int{0}
}

func (m *Teacher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Teacher.Unmarshal(m, b)
}
func (m *Teacher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Teacher.Marshal(b, m, deterministic)
}
func (m *Teacher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Teacher.Merge(m, src)
}
func (m *Teacher) XXX_Size() int {
	return xxx_messageInfo_Teacher.Size(m)
}
func (m *Teacher) XXX_DiscardUnknown() {
	xxx_messageInfo_Teacher.DiscardUnknown(m)
}

var xxx_messageInfo_Teacher proto.InternalMessageInfo

func (m *Teacher) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Teacher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Teacher) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*Teacher)(nil), "types.Teacher")
}

func init() { proto.RegisterFile("types/teacher.proto", fileDescriptor_9ade93e9f120fc16) }

var fileDescriptor_9ade93e9f120fc16 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2f, 0x49, 0x4d, 0x4c, 0xce, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x0b, 0x2a, 0xd9, 0x73, 0xb1, 0x87, 0x40, 0xc4, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x98, 0x32, 0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12,
	0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xc4,
	0xf4, 0x54, 0x09, 0x66, 0xb0, 0x22, 0x10, 0xd3, 0x89, 0x3d, 0x0a, 0x62, 0x52, 0x12, 0x1b, 0xd8,
	0x5c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xb6, 0xc7, 0x44, 0x6e, 0x00, 0x00, 0x00,
}
